const types = {
  LOGGOUT: "LOGGOUT",
  SET_TOKEN: "SET_TOKEN",
  LOGGIN: "LOGGIN",
  USER_DETAILS: "USER_DETAILS",
  REDIRECT: "REDIRECT",
  //   RESET_PASSWORD: "RESET_PASSWORD",
  //   FORGOT_PASSWORD: "FORGOT_PASSWORD",
  //   CREATE_ACCOUNT: "CREATE_ACCOUNT",
};

export default types;
